import Head from "next/head";
import Image from "next/image";
import { useSession, signIn, signOut } from "next-auth/react";
import Header from "../components/molecules/header";
import Layout from "../components/organisms/layout";
import Section from "../components/molecules/section";
import CtaButton from "../components/atoms/Ctabutton";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <Section>
          <h2 className="text-3xl my-3">申し込む</h2>
          <CtaButton linkto="/" text="Create mine in 1 minute."></CtaButton>
          <p>Instagramアカウント で活動の様子をご覧ください。</p>
        </Section>
      </Layout>
    </div>
  );
}
